#%RAML 1.0
title: oxid shop API
baseUri: api/{version}
version: v1

annotationTypes: !include annotations.raml
resourceTypes: !include resources.raml
traits: !include traits.raml
types: !include types.raml

