#%RAML 1.0 Library

Country: !include Country.raml
User:
  type: object
Group:
  type: object
Subscription:
  type: object
Remark:
  type: object
Address:
  type: object
Article:
  type: object
ArticleCategory:
  type: object
Vendor:
  type: object
Manufacturer:
  type: object
DeliveryRule:
  type: object
DeliveryMethod:
  type: object
Discount:
  type: object
PriceScale:
  type: object
PriceAlarm:
  type: object
ListMania:
  type: object
Rating:
  type: object
Review:
  type: object
PaymentMethod:
  type: object
UserPayment:
  type: object
Wrapping:
  type: object
OrderArticle:
  type: object
OrderFile:
  type: object
Order:
  type: object
Basket:
  type: object
BasketItem:
  type: object
CouponSeries:
  type: object
Coupon:
  type: object
News:
  type: object
Newsletter:
  type: object
Content:
  type: object
Block:
  type: object
Link:
  type: object
Media:
  type: object
Download:
  type: object
GuestBook:
  type: object
Seo:
  type: object
SeoHit:
  type: object
SeoLog:
  type: object
Shop:
  type: object
